language: csharp
os:
  - linux
  - osx
osx_image: xcode8.3
solution: MoreLinq.sln
mono: 5.0.1
dist: trusty
sudo: required
dotnet: 2.0.0
env:
  - CONFIGURATION=Debug
  - CONFIGURATION=Release
addons:
  apt:
    sources:
    - sourceline: 'deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty main'
      key_url: 'https://packages.microsoft.com/keys/microsoft.asc'
    packages:
    - dotnet-hostfxr-1.0.1
    - dotnet-sharedframework-microsoft.netcore.app-1.0.5

before_install:
  - msbuild /version
  - |
    # Handle too many files on OS X
    if [ "$TRAVIS_OS_NAME" == "osx" ] || [ `uname` == "Darwin" ]; then
      ulimit -n 4096
    fi

install:
  - dotnet restore

script:
  - ./msbuild.sh /v:m /p:Configuration=$CONFIGURATION
  - dotnet exec MoreLinq.Test/bin/$CONFIGURATION/netcoreapp1.0/MoreLinq.Test.dll
  - dotnet exec MoreLinq.Test/bin/$CONFIGURATION/netcoreapp2.0/MoreLinq.Test.dll
  - mono MoreLinq.Test/bin/$CONFIGURATION/net451/MoreLinq.Test.exe
